name: second workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: using actions
      uses: actions/checkout@v4
    - name: welcome message
      run: ls > ls.txt
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ls.txt
  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
         name: my-artifact
         path: kubernetes-project
      - run: cat ls.txt
        